import { luxuryTheme } from "./theme";

export const colors = {
  background: luxuryTheme.background,
  surface: luxuryTheme.muted,
  surfaceElevated: luxuryTheme.card,
  cream: luxuryTheme.muted,
  warmWhite: luxuryTheme.card,
  foreground: luxuryTheme.textPrimary,
  headerBrown: luxuryTheme.dark,
  primaryAccent: luxuryTheme.accentStrong,
  accent: luxuryTheme.accentStrong,
  interactive: luxuryTheme.accentStrong,
  gold: luxuryTheme.accentStrong,
  goldMuted: luxuryTheme.accentStrong,
  goldDecorative: luxuryTheme.accent,
  accentDecorative: luxuryTheme.accent,
  onAccent: luxuryTheme.onAccent,
  textPrimary: luxuryTheme.textPrimary,
  textSecondary: luxuryTheme.textSecondary,
  charcoal: luxuryTheme.textPrimary,
  brown: luxuryTheme.dark,
  brownSoft: luxuryTheme.textSecondary,
  border: luxuryTheme.border,
  borderSoft: luxuryTheme.border,
  borderStrong: luxuryTheme.borderStrong,
  navbarBackground: luxuryTheme.card,
  white: luxuryTheme.card,
  black: luxuryTheme.dark,
  muted: luxuryTheme.muted,
  media: luxuryTheme.media,
  divider: luxuryTheme.border,
  success: luxuryTheme.success,
  warning: luxuryTheme.warning,
  error: luxuryTheme.error,
  overlay: luxuryTheme.overlay,
  shadow: luxuryTheme.shadow,
  transparent: luxuryTheme.transparent,
} as const;

export type AppColors = typeof colors;
